#!/usr/bin/env bash
i='0'
while ((i < 100))
do
	((i++))
	if [ $(($i % 3)) == 0 ] && [ $(($i % 5)) == 0 ]
	then
		echo "Fizzbuzz"
	elif [ $(($i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $(($i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
done
