#!/usr/bin/env bash
# This script gives you information about the holbertonschool file.

test=./holbertonschool
if [ -e "$test" ]
then
	echo "holbertonschool file exists"
	if [ -n "$test" ]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi

	if [ -h $test ]
	then
		echo ''
	elif [ -f $test ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
